# Installation: https://github.com/jlesage/docker-dupeguru
version: '3.9'
services:
  dupeguru:
    container_name: dupeguru
    image: jlesage/dupeguru:v24.01.1
    environment:
      - TZ=${DUPEGURU_TZ}
      - DISPLAY_WIDTH=${DUPEGURU_DISPLAY_WIDTH}
      - DISPLAY_HEIGHT=${DUPEGURU_DISPLAY_HEIGHT}
      - SECURE_CONNECTION=${DUPEGURU_SECURE_CONNECTION}
      - ENABLE_CJK_FONT=${DUPEGURU_ENABLE_CJK_FONT}
      - UMASK=${DUPEGURU_UMASK}
    ports:
      - 57801:5800
      - 7901:5900
    volumes:
      - /opt/appdata/dupeguru:/config:rw
      - /opt/appdata/dupeguru/storage:/storage:rw
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
