# Installation: https://github.com/techno-tim/littlelink-server

services:
  littlelink-server:
    image: timothystewart6/littlelink-server:latest
    container_name: littlelink-server
    environment:
      - META_TITLE=${LITTLELINK_SERVER_META_TITLE}
      - META_DESCRIPTION=${LITTLELINK_SERVER_META_DESCRIPTION}
      - META_AUTHOR=${LITTLELINK_SERVER_META_AUTHOR}
      - META_KEYWORDS=${LITTLELINK_SERVER_META_KEYWORDS}
      - LANG=${LITTLELINK_SERVER_LANG}
      - META_INDEX_STATUS=${LITTLELINK_SERVER_META_INDEX_STATUS}
      - THEME=${LITTLELINK_SERVER_THEME}
      - FAVICON_URL=${LITTLELINK_SERVER_FAVICON_URL}
      - AVATAR_URL=${LITTLELINK_SERVER_AVATAR_URL}
      - AVATAR_2X_URL=${LITTLELINK_SERVER_AVATAR_2X_URL}
      - AVATAR_ALT=${LITTLELINK_SERVER_AVATAR_ALT}
      - NAME=${LITTLELINK_SERVER_NAME}
      - BIO=${LITTLELINK_SERVER_BIO}
      - FOOTER=${LITTLELINK_SERVER_FOOTER}
      - GITHUB=${LITTLELINK_SERVER_GITHUB}
      - TWITTER=${LITTLELINK_SERVER_TWITTER}
      - INSTAGRAM=${LITTLELINK_SERVER_INSTAGRAM}
      - YOUTUBE=${LITTLELINK_SERVER_YOUTUBE}
      - TWITCH=${LITTLELINK_SERVER_TWITCH}
      - DISCORD=${LITTLELINK_SERVER_DISCORD}
      - TIKTOK=${LITTLELINK_SERVER_TIKTOK}
      - KIT=${LITTLELINK_SERVER_KIT}
      - FACEBOOK=${LITTLELINK_SERVER_FACEBOOK}
      - FACEBOOK_MESSENGER=${LITTLELINK_SERVER_FACEBOOK_MESSENGER}
      - LINKED_IN=${LITTLELINK_SERVER_LINKED_IN}
      - PRODUCT_HUNT=${LITTLELINK_SERVER_PRODUCT_HUNT}
      - SNAPCHAT=${LITTLELINK_SERVER_SNAPCHAT}
      - SPOTIFY=${LITTLELINK_SERVER_SPOTIFY}
      - REDDIT=${LITTLELINK_SERVER_REDDIT}
      - MEDIUM=${LITTLELINK_SERVER_MEDIUM}
      - PINTEREST=${LITTLELINK_SERVER_PINTEREST}
      - EMAIL=${LITTLELINK_SERVER_EMAIL}
      - EMAIL_TEXT=${LITTLELINK_SERVER_EMAIL_TEXT}
      - EMAIL_ALT=${LITTLELINK_SERVER_EMAIL_ALT}
      - EMAIL_ALT_TEXT=${LITTLELINK_SERVER_EMAIL_ALT_TEXT}
      - SOUND_CLOUD=${LITTLELINK_SERVER_SOUND_CLOUD}
      - FIGMA=${LITTLELINK_SERVER_FIGMA}
      - TELEGRAM=${LITTLELINK_SERVER_TELEGRAM}
      - TUMBLR=${LITTLELINK_SERVER_TUMBLR}
      - STEAM=${LITTLELINK_SERVER_STEAM}
      - VIMEO=${LITTLELINK_SERVER_VIMEO}
      - WORDPRESS=${LITTLELINK_SERVER_WORDPRESS}
      - GOODREADS=${LITTLELINK_SERVER_GOODREADS}
      - SKOOB=${LITTLELINK_SERVER_SKOOB}
      - LETTERBOXD=${LITTLELINK_SERVER_LETTERBOXD}
      - MASTODON=${LITTLELINK_SERVER_MASTODON}
      - MICRO_BLOG=${LITTLELINK_SERVER_MICRO_BLOG}
      - WHATSAPP=${LITTLELINK_SERVER_WHATSAPP}
      - STRAVA=${LITTLELINK_SERVER_STRAVA}
      - BUYMEACOFFEE=${LITTLELINK_SERVER_BUYMEACOFFEE}
      - GITLAB=${LITTLELINK_SERVER_GITLAB}
      - PATREON=${LITTLELINK_SERVER_PATREON}
      - DEVTO=${LITTLELINK_SERVER_DEVTO}
      - UMAMI_WEBSITE_ID=${LITTLELINK_SERVER_UMAMI_WEBSITE_ID}
      - UMAMI_APP_URL=${LITTLELINK_SERVER_UMAMI_APP_URL}
      - BUTTON_ORDER=${LITTLELINK_SERVER_BUTTON_ORDER}
      - PAYPAL=${LITTLELINK_SERVER_PAYPAL}
      - SLACK=${LITTLELINK_SERVER_SLACK}
      - STACKOVERFLOW=${LITTLELINK_SERVER_STACKOVERFLOW}
      - LASTFM=${LITTLELINK_SERVER_LASTFM}
      - GITEA=${LITTLELINK_SERVER_GITEA}
      - POLYWORK=${LITTLELINK_SERVER_POLYWORK}
      - SIGNAL=${LITTLELINK_SERVER_SIGNAL}
      - UNTAPPD=${LITTLELINK_SERVER_UNTAPPD}
      - BUTTON_TARGET=${LITTLELINK_SERVER_BUTTON_TARGET}
      - INSTANTGAMING=${LITTLELINK_SERVER_INSTANTGAMING}
      - GHOST=${LITTLELINK_SERVER_GHOST}
      - TRAKT=${LITTLELINK_SERVER_TRAKT}
      - CASHAPP=${LITTLELINK_SERVER_CASHAPP}
      - TEESPRING=${LITTLELINK_SERVER_TEESPRING}
      - XING=${LITTLELINK_SERVER_XING}
      - KEYBASE=${LITTLELINK_SERVER_KEYBASE}
      - ONLYFANS=${LITTLELINK_SERVER_ONLYFANS}
      - SESSION=${LITTLELINK_SERVER_SESSION}
      - THREEMA=${LITTLELINK_SERVER_THREEMA}
      - STREAMLABS=${LITTLELINK_SERVER_STREAMLABS}
      - PRIVATEBIN=${LITTLELINK_SERVER_PRIVATEBIN}
      - AMAZON_AFFILIATE=${LITTLELINK_SERVER_AMAZON_AFFILIATE}
      - APPLE_MUSIC=${LITTLELINK_SERVER_APPLE_MUSIC}
      - VENMO=${LITTLELINK_SERVER_VENMO}
      - STATUS=${LITTLELINK_SERVER_STATUS}
      - MATRIX=${LITTLELINK_SERVER_MATRIX}
      - ANILIST=${LITTLELINK_SERVER_ANILIST}
      - GITBUCKET=${LITTLELINK_SERVER_GITBUCKET}
      - SHAZAM=${LITTLELINK_SERVER_SHAZAM}
      - TPDB=${LITTLELINK_SERVER_TPDB}
      - FLICKR=${LITTLELINK_SERVER_FLICKR}
      - OSU=${LITTLELINK_SERVER_OSU}
      - LINE=${LITTLELINK_SERVER_LINE}
      - DESIGNBYHUMANS=${LITTLELINK_SERVER_DESIGNBYHUMANS}
      - DOCKERHUB=${LITTLELINK_SERVER_DOCKERHUB}
      - VERO=${LITTLELINK_SERVER_VERO}
      - MYANIMELIST=${LITTLELINK_SERVER_MYANIMELIST}
      - OG_SITE_NAME=${LITTLELINK_SERVER_OG_SITE_NAME}
      - OG_TITLE=${LITTLELINK_SERVER_OG_TITLE}
      - OG_DESCRIPTION=${LITTLELINK_SERVER_OG_DESCRIPTION}
      - OG_URL=${LITTLELINK_SERVER_OG_URL}
      - OG_IMAGE=${LITTLELINK_SERVER_OG_IMAGE}
      - OG_IMAGE_WIDTH=${LITTLELINK_SERVER_OG_IMAGE_WIDTH}
      - OG_IMAGE_HEIGHT=${LITTLELINK_SERVER_OG_IMAGE_HEIGHT}
      - TWITTER_CARD=${LITTLELINK_SERVER_TWITTER_CARD}
      - TWITTER_IMAGE=${LITTLELINK_SERVER_TWITTER_IMAGE}
      - TWITTER_SITE=${LITTLELINK_SERVER_TWITTER_SITE}
      - TWITTER_CREATOR=${LITTLELINK_SERVER_TWITTER_CREATOR}
      - SHARE=${LITTLELINK_SERVER_SHARE}
      - FIVEHUNDREDPX=${LITTLELINK_SERVER_FIVEHUNDREDPX}
    ports:
      - 1014:3000
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
